# ~/.config/efm-langserver/config.yaml
# Thanks to reykjalin for providing these sensible defaults!

version: 2
# NOTE: Update this path to your own home directory after install
log-file: ~/.cache/efm-langserver/efm-langserver.log
log-level: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:

  javascript-eslint: &javascript-eslint
    lint-command: 'npx eslint -f ~/.config/efm-langserver/eslint-formatter.js --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-after-open: true
    lint-formats:
      - "%f:%l:%c:%tarning:%m"
      - "%f:%l:%c:%trror:%m"
    root-markers:
      - eslint.config.js
      - package.json

  stylelint: &stylelint
    # lint-command: 'npx stylelint --formatter compact --stdin-filename ${INPUT}'
    lint-command: 'npx stylelint --formatter compact --stdin --no-cache --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-after-open: true
    lint-formats:
      - "%f: line %l, col %c, %tarning - %m"
      - "%f: line %l, col %c, %trror - %m"
    root-markers:
      - .stylelintignore
      - .stylelint
      - package.json

languages:

  typescript:
    - <<: *javascript-eslint

  typescriptreact:
    - <<: *javascript-eslint

  javascript:
    - <<: *javascript-eslint

  javascriptreact:
    - <<: *javascript-eslint

  css:
    - <<: *stylelint

  scss:
    - <<: *stylelint
